version: "3.5"

services:
  moose-gh-pages-checks:
    image: moose/gh-pages-checks
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moose-gh-pages-checks
    volumes:
      - .:/moose
    stdin_open: true
    tty: true
    command: npx linkinator https://flightcontrol-master.github.io/MOOSE_DOCS/ --config /moose/config.json
